version: '3'
services:
    rabbitmq:
        image: rabbitmq:3.7.18-management-alpine
        ports:
        - 5672:5672 # AMQP port
        - 15672:15672 # Management console HTTP port
        environment:
            RABBITMQ_DEFAULT_USER: rabbitmq
            RABBITMQ_DEFAULT_PASS: password1
    manager:
        build: ./simple-messaging-manager
        ports:
        - 8001:8080
        depends_on:
        - rabbitmq
    worker:
        build: ./simple-messaging-worker
        ports:
        - 8002-8011:8080
        depends_on:
        - rabbitmq